{
    "assignee": null,
    "assignees": [],
    "body": "Calling `cythonize` with an instance of `setuptools.extension.Extension` raises an `AttributeError`.\r\nThe cause is that `setuptools.extension.Extension` subclasses [`distutils.extension.Extension`](https://github.com/python/cpython/blob/ee324a8f516318e84914ebd18f3e8068faec14f9/Lib/distutils/extension.py#L26), which is defined as an old-style class. These types can be [confirmed](http://stackoverflow.com/a/2654781/1959808) with:\r\n\r\n```python\r\nimport distutils.core.Extension\r\nimport types\r\nimport setuptools.extension.Extension\r\n\r\nassert type(distutils.core.Extension) != types.TypeType\r\nassert type(setuptools.extension.Extension) != types.TypeType\r\n```\r\n\r\nThis behavior arises with:\r\n- `setuptools == 28.7.0`\r\n- `cython == 0.25.1`\r\n\r\nThis issue did not exist with earlier `cython` versions.\r\nCloser examination of the [docstring](https://github.com/cython/cython/blob/278a567621d586af74a1c845de0a1426b686c72e/Cython/Build/Dependencies.py#L768) of function `cythonize` reveals that one should pass a list of `Extension` objects:\r\n\r\n```\r\nAs module list, pass either a glob pattern, a list of glob patterns or a list of\r\n    Extension objects.  The latter allows you to configure the extensions separately\r\n    through the normal distutils options.\r\n```\r\n\r\nSo, my usage was wrong. Indeed, passing a `list` of `Extension` objects avoids the error. Since this error did not exist in the past, and because I believe that I followed some example when I initially wrote the code to pass an extension itself, I wonder whether this case is supposed to be supported, or if not, whether it should be emphasized in the docstring. Tracing the cause took a long time, especially because I assumed that `cythonize` was already properly called.\r\n\r\nOne workaround is to [create a new-style subclass](https://github.com/johnyf/dd/blob/af59d90a893c27d3070d6584297f671eb4fe2c20/download.py#L79):\r\n\r\n```python\r\nclass Extension(setuptools.extension.Extension,object):\r\n    pass\r\n```\r\n\r\nThis works fine. Traceback from [`dd/download.py`](https://github.com/johnyf/dd/blob/af59d90a893c27d3070d6584297f671eb4fe2c20/download.py#L118) when `object` is removed from the above subclass definition:\r\n\r\n```python\r\ndd:python setup.py install --cudd --linetrace\r\ncompile Cython extensions with line tracing\r\nTraceback (most recent call last):\r\n  File \"setup.py\", line 136, in <module>\r\n    run_setup()\r\n  File \"setup.py\", line 93, in run_setup\r\n    extensions = download.extensions(directives)\r\n  File \"/path/dd/download.py\", line 119, in extensions\r\n    v, compiler_directives=directives)\r\n  File \"~/.virtualenvs/dev/lib/python2.7/site-packages/Cython/Build/Dependencies.py\", line 809, in cythonize\r\n    aliases=aliases)\r\n  File \"~/.virtualenvs/dev/lib/python2.7/site-packages/Cython/Build/Dependencies.py\", line 648, in create_extension_list\r\n    elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):\r\n  File \"~/.virtualenvs/dev/lib/python2.7/abc.py\", line 144, in __instancecheck__\r\n    return cls.__subclasscheck__(subtype)\r\n  File \"~/.virtualenvs/dev/lib/python2.7/abc.py\", line 180, in __subclasscheck__\r\n    if issubclass(subclass, scls):\r\n  File \"~/.virtualenvs/dev/lib/python2.7/abc.py\", line 180, in __subclasscheck__\r\n    if issubclass(subclass, scls):\r\n  File \"/home/ioannis/.virtualenvs/dev/lib/python2.7/abc.py\", line 161, in __subclasscheck__\r\n    ok = cls.__subclasshook__(subclass)\r\n  File \"~/.virtualenvs/dev/lib/python2.7/site-packages/backports_abc.py\", line 66, in __subclasshook__\r\n    mro = C.__mro__\r\nAttributeError: class Extension has no attribute '__mro__'\r\n```\r\n\r\nThe failure is due to the `isinstance(patterns, collections.Iterable)`. It can be reproduced as follows:\r\n\r\n```python\r\nimport collections\r\n\r\nfrom Cython.Build import cythonize\r\nfrom setuptools.extension import Extension\r\n\r\na = Extension('foo', sources=['foo.pyx'])\r\n\r\nisinstance([a], collections.Iterable)  # works fine\r\nisinstance(a, collections.Iterable)  # raises `AttributeError`\r\n```\r\n\r\nI will report this issue also to `setuptools`, though it seems to me that defining an old-style class is intentional there.",
    "closed_at": null,
    "comment_data": [
        {
            "body": "Exactly seeing this error in my travis tests after update to 0.25.1. \r\n\r\n(updated since I see the workaround)",
            "created_at": "2016-10-30T00:57:07Z",
            "html_url": "https://github.com/cython/cython/issues/1507#issuecomment-257125085",
            "id": 257125085,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1507",
            "updated_at": "2016-10-30T00:58:26Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/257125085",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/138060?v=3",
                "events_url": "https://api.github.com/users/rainwoodman/events{/privacy}",
                "followers_url": "https://api.github.com/users/rainwoodman/followers",
                "following_url": "https://api.github.com/users/rainwoodman/following{/other_user}",
                "gists_url": "https://api.github.com/users/rainwoodman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/rainwoodman",
                "id": 138060,
                "login": "rainwoodman",
                "organizations_url": "https://api.github.com/users/rainwoodman/orgs",
                "received_events_url": "https://api.github.com/users/rainwoodman/received_events",
                "repos_url": "https://api.github.com/users/rainwoodman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/rainwoodman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rainwoodman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/rainwoodman"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1507/comments",
    "created_at": "2016-10-29T03:06:54Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3135273?v=3",
                "events_url": "https://api.github.com/users/johnyf/events{/privacy}",
                "followers_url": "https://api.github.com/users/johnyf/followers",
                "following_url": "https://api.github.com/users/johnyf/following{/other_user}",
                "gists_url": "https://api.github.com/users/johnyf/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/johnyf",
                "id": 3135273,
                "login": "johnyf",
                "organizations_url": "https://api.github.com/users/johnyf/orgs",
                "received_events_url": "https://api.github.com/users/johnyf/received_events",
                "repos_url": "https://api.github.com/users/johnyf/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/johnyf/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/johnyf/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/johnyf"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2016-10-29T03:15:48Z",
            "event": "renamed",
            "id": 840813383,
            "rename": {
                "from": "cythonize fails when given setuptools.extension.Extension",
                "to": "cythonize fails when given `setuptools.extension.Extension`"
            },
            "url": "https://api.github.com/repos/cython/cython/issues/events/840813383"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/138060?v=3",
                "events_url": "https://api.github.com/users/rainwoodman/events{/privacy}",
                "followers_url": "https://api.github.com/users/rainwoodman/followers",
                "following_url": "https://api.github.com/users/rainwoodman/following{/other_user}",
                "gists_url": "https://api.github.com/users/rainwoodman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/rainwoodman",
                "id": 138060,
                "login": "rainwoodman",
                "organizations_url": "https://api.github.com/users/rainwoodman/orgs",
                "received_events_url": "https://api.github.com/users/rainwoodman/received_events",
                "repos_url": "https://api.github.com/users/rainwoodman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/rainwoodman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rainwoodman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/rainwoodman"
            },
            "commit_id": "485baba365fb72fdf78a7eeb0308c25536d23e1e",
            "commit_url": "https://api.github.com/repos/rainwoodman/pfft-python/commits/485baba365fb72fdf78a7eeb0308c25536d23e1e",
            "created_at": "2016-10-30T00:59:29Z",
            "event": "referenced",
            "id": 841053195,
            "url": "https://api.github.com/repos/cython/cython/issues/events/841053195"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1507/events",
    "html_url": "https://github.com/cython/cython/issues/1507",
    "id": 186055873,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1507/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1507,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "cythonize fails when given `setuptools.extension.Extension`",
    "updated_at": "2016-10-30T00:58:26Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1507",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3135273?v=3",
        "events_url": "https://api.github.com/users/johnyf/events{/privacy}",
        "followers_url": "https://api.github.com/users/johnyf/followers",
        "following_url": "https://api.github.com/users/johnyf/following{/other_user}",
        "gists_url": "https://api.github.com/users/johnyf/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/johnyf",
        "id": 3135273,
        "login": "johnyf",
        "organizations_url": "https://api.github.com/users/johnyf/orgs",
        "received_events_url": "https://api.github.com/users/johnyf/received_events",
        "repos_url": "https://api.github.com/users/johnyf/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/johnyf/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/johnyf/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/johnyf"
    }
}