{
    "assignee": null,
    "assignees": [],
    "body": "I cannot successfully obtain a report of coverage for the Cython module [`dd.cudd`](https://github.com/johnyf/dd/blob/master/dd/cudd.pyx). I have:\n- followed the [Cython instructions for enabling coverage analysis](http://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html#enabling-coverage-analysis)\n- ensured that `coverage.py` with its [C extension](https://coverage.readthedocs.io/en/coverage-4.2/plugins.html) are installed, in order for the `Cython.Coverage` plugin to work.\n\nI am using `nosetests`---I do not know whether `nose` can cause additional difficulties.\n\nDirectory layout under `/path` roughly:\n\n```\ndd/\ntests/\n```\n\nNormally, I run `nosetests` within `tests/`, because I want to ensure that `nosetests` will import `dd` from `site-packages` (I have also tried the `-w` option of `nosetests`).\nI have tried running `nosetests` both inside the `tests/` directory, and above it.\n`nose` does not report any results for `cudd.pyx`.\n\nWhen `nose --with-coverage --cover-package=dd` runs under `tests/`, it creates a `.coverage` that mentions both a `/path/tests/dd/cudd.pyx` file (nonexistent), as well as the existing `/path/dd/dd/cudd.pyx`. For the existing file, `coverage report` complains that\n\n```\n/path/dd/dd/cudd.pyx   NotPython:\nCouldn't parse '/path/dd/dd/cudd.pyx' as Python source: 'invalid syntax' at line 20\n```\n\nAlso, manually editing the wrong path reported in `.coveragerc` produces again the above error.\n\nThese observations are with:\n- `cython == 0.25.1`\n- `nose == 1.3.7`\n- `coverage == 4.2`\n\nHow can I get coverage to be reported for Cython modules? It seems that this may be a problem both with paths that `coverage.py` reports, and with failure of `coverage.py` to parse Cython syntax. I am unsure whether this should be addressed by `cython` (e.g., in the `coverage.py` plugin `Cython.Coverage`), or by `coverage.py`, or both.\n\nMay have some relevance to #1461.\n",
    "closed_at": null,
    "comment_data": [
        {
            "body": "The problem likely relates to testing the package installed under `site-packages`, in contrast to:\r\n\r\n[\"Then make sure you build your project in place (`python setup.py build_ext --inplace`) so that the generated C/C++ code files can be found right next to the binary modules and their sources.\"](http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html)\r\n\r\nand\r\n\r\n[\"coverage report requires a local install\"](https://github.com/jswhit/pyproj/commit/12e3d45#diff-354f30a63fb0907d4ad57269548329e3R51).",
            "created_at": "2016-11-27T03:09:05Z",
            "html_url": "https://github.com/cython/cython/issues/1508#issuecomment-263099621",
            "id": 263099621,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1508",
            "updated_at": "2016-11-27T03:09:05Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/263099621",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3135273?v=3",
                "events_url": "https://api.github.com/users/johnyf/events{/privacy}",
                "followers_url": "https://api.github.com/users/johnyf/followers",
                "following_url": "https://api.github.com/users/johnyf/following{/other_user}",
                "gists_url": "https://api.github.com/users/johnyf/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/johnyf",
                "id": 3135273,
                "login": "johnyf",
                "organizations_url": "https://api.github.com/users/johnyf/orgs",
                "received_events_url": "https://api.github.com/users/johnyf/received_events",
                "repos_url": "https://api.github.com/users/johnyf/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/johnyf/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/johnyf/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/johnyf"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1508/comments",
    "created_at": "2016-10-29T03:52:11Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1508/events",
    "html_url": "https://github.com/cython/cython/issues/1508",
    "id": 186057475,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1508/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1508,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "cannot report test coverage",
    "updated_at": "2016-11-27T03:09:05Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1508",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3135273?v=3",
        "events_url": "https://api.github.com/users/johnyf/events{/privacy}",
        "followers_url": "https://api.github.com/users/johnyf/followers",
        "following_url": "https://api.github.com/users/johnyf/following{/other_user}",
        "gists_url": "https://api.github.com/users/johnyf/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/johnyf",
        "id": 3135273,
        "login": "johnyf",
        "organizations_url": "https://api.github.com/users/johnyf/orgs",
        "received_events_url": "https://api.github.com/users/johnyf/received_events",
        "repos_url": "https://api.github.com/users/johnyf/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/johnyf/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/johnyf/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/johnyf"
    }
}