{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I am having trouble compiling Cython 0.25.2 using icc. (version 17.0.1)\r\n\r\nThe problems occur when trying to compile the following files with the corresponding compiler options:\r\n\r\n`icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/Cython-0.25.2/Cython/Compiler/Parsing.o -o build/lib.linux-x86_64-3.5/Cython/Compiler/Parsing.cpython-35m-x86_64-linux-gnu.so`\r\n\r\n`icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/Cython-0.25.2/Cython/Compiler/Code.o -o build/lib.linux-x86_64-3.5/Cython/Compiler/Code.cpython-35m-x86_64-linux-gnu.so`\r\n\r\n`icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/Cython-0.25.2/Cython/Tempita/_tempita.o -o build/lib.linux-x86_64-3.5/Cython/Tempita/_tempita.cpython-35m-x86_64-linux-gnu.so`\r\n\r\nAll three led to this error:\r\n```\r\n\": internal error: 010101_(5000 + 54)\r\n\r\nicc: error #10014: problem during multi-file optimization compilation (code 4)\r\nerror: command 'icc' failed with exit status 4\r\n```\r\nI worked around it by compiling the three files manually with `icc -shared -O0` instead, and I could finish building and installing Cython with no further problems.\r\n\r\nAlso, I could run\r\n```\r\ncd Demos\r\npython setup.py build_ext --inplace\r\n```\r\n\r\nAnd the examples:\r\n\r\n```\r\npython run_primes.py\r\npython run_spam.py\r\npython run_numeric_demo.py\r\n```\r\nworked with no problems.",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "OWNER",
            "body": "Have you verified that this is not an ICC bug?\n\nOn Jan 24, 2017 12:48 PM, \"dbalague\" <notifications@github.com> wrote:\n\n> I am having trouble compiling Cython 0.25.2 using icc. (version 17.0.1)\n>\n> The problems occur when trying to compile the following files with the\n> corresponding compiler options:\n>\n> icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/\n> Cython-0.25.2/Cython/Compiler/Parsing.o -o build/lib.linux-x86_64-3.5/\n> Cython/Compiler/Parsing.cpython-35m-x86_64-linux-gnu.so\n>\n> icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/\n> Cython-0.25.2/Cython/Compiler/Code.o -o build/lib.linux-x86_64-3.5/\n> Cython/Compiler/Code.cpython-35m-x86_64-linux-gnu.so\n>\n> icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/\n> Cython-0.25.2/Cython/Tempita/_tempita.o -o build/lib.linux-x86_64-3.5/\n> Cython/Tempita/_tempita.cpython-35m-x86_64-linux-gnu.so\n>\n> All three led to this error:\n>\n> \": internal error: 010101_(5000 + 54)\n>\n> icc: error #10014: problem during multi-file optimization compilation (code 4)\n> error: command 'icc' failed with exit status 4\n>\n> I worked around it by compiling the three files manually with icc -shared\n> -O0 instead, and I could finish building and installing Cython with no\n> further problems.\n>\n> Also, I could run\n>\n> cd Demos\n> python setup.py build_ext --inplace\n>\n> And the examples:\n>\n> python run_primes.py\n> python run_spam.py\n> python run_numeric_demo.py\n>\n> worked with no problems.\n>\n> â€”\n> You are receiving this because you are subscribed to this thread.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/cython/cython/issues/1591>, or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAdqgXe1SRSTsMofBYgCeMsTHq82fdyhks5rVmOogaJpZM4LsxFY>\n> .\n>\n",
            "created_at": "2017-01-24T21:56:15Z",
            "html_url": "https://github.com/cython/cython/issues/1591#issuecomment-274951756",
            "id": 274951756,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1591",
            "updated_at": "2017-01-24T21:56:15Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/274951756",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/486017?v=4",
                "events_url": "https://api.github.com/users/robertwb/events{/privacy}",
                "followers_url": "https://api.github.com/users/robertwb/followers",
                "following_url": "https://api.github.com/users/robertwb/following{/other_user}",
                "gists_url": "https://api.github.com/users/robertwb/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/robertwb",
                "id": 486017,
                "login": "robertwb",
                "organizations_url": "https://api.github.com/users/robertwb/orgs",
                "received_events_url": "https://api.github.com/users/robertwb/received_events",
                "repos_url": "https://api.github.com/users/robertwb/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/robertwb/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/robertwb/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/robertwb"
            }
        },
        {
            "author_association": "NONE",
            "body": "I ran into the same problem with cython 0.27.2 and icc version 17.0.1 (gcc version 4.8.5 compatibility). I do not have this problem if I use cython 0.26.1",
            "created_at": "2017-10-27T21:01:12Z",
            "html_url": "https://github.com/cython/cython/issues/1591#issuecomment-340084224",
            "id": 340084224,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1591",
            "updated_at": "2017-10-27T21:01:12Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/340084224",
            "user": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/3187259?v=4",
                "events_url": "https://api.github.com/users/smcantab/events{/privacy}",
                "followers_url": "https://api.github.com/users/smcantab/followers",
                "following_url": "https://api.github.com/users/smcantab/following{/other_user}",
                "gists_url": "https://api.github.com/users/smcantab/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/smcantab",
                "id": 3187259,
                "login": "smcantab",
                "organizations_url": "https://api.github.com/users/smcantab/orgs",
                "received_events_url": "https://api.github.com/users/smcantab/received_events",
                "repos_url": "https://api.github.com/users/smcantab/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/smcantab/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/smcantab/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/smcantab"
            }
        },
        {
            "author_association": "NONE",
            "body": "I guess I did not specify the GCC compatibility version. It was exactly the same as yours:\r\nicc version 17.0.1 (gcc version 4.8.5 compatibility)",
            "created_at": "2017-10-27T21:17:12Z",
            "html_url": "https://github.com/cython/cython/issues/1591#issuecomment-340088165",
            "id": 340088165,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1591",
            "updated_at": "2017-10-27T21:17:12Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/340088165",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/25331181?v=4",
                "events_url": "https://api.github.com/users/dbalague/events{/privacy}",
                "followers_url": "https://api.github.com/users/dbalague/followers",
                "following_url": "https://api.github.com/users/dbalague/following{/other_user}",
                "gists_url": "https://api.github.com/users/dbalague/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/dbalague",
                "id": 25331181,
                "login": "dbalague",
                "organizations_url": "https://api.github.com/users/dbalague/orgs",
                "received_events_url": "https://api.github.com/users/dbalague/received_events",
                "repos_url": "https://api.github.com/users/dbalague/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/dbalague/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dbalague/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/dbalague"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1591/comments",
    "created_at": "2017-01-24T20:48:39Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1591/events",
    "html_url": "https://github.com/cython/cython/issues/1591",
    "id": 202935820,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1591/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1591,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Problems building Cython with icc",
    "updated_at": "2017-10-27T21:17:12Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1591",
    "user": {
        "avatar_url": "https://avatars0.githubusercontent.com/u/25331181?v=4",
        "events_url": "https://api.github.com/users/dbalague/events{/privacy}",
        "followers_url": "https://api.github.com/users/dbalague/followers",
        "following_url": "https://api.github.com/users/dbalague/following{/other_user}",
        "gists_url": "https://api.github.com/users/dbalague/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/dbalague",
        "id": 25331181,
        "login": "dbalague",
        "organizations_url": "https://api.github.com/users/dbalague/orgs",
        "received_events_url": "https://api.github.com/users/dbalague/received_events",
        "repos_url": "https://api.github.com/users/dbalague/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/dbalague/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dbalague/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/dbalague"
    }
}