{
    "assignee": null,
    "assignees": [],
    "body": "Python 3.5, Cython 0.25.2 and numpy 1.12.1.\r\n```\r\n======================================================================\r\nFAIL: numpy_test ()\r\nDoctest: numpy_test\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/nix/store/zvm545rqc4d97caqq9h7344bnd06jhzb-python3-3.5.3/lib/python3.5/doctest.py\", line 2190, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_test\r\n  File \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/c/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line 1, in numpy_test\r\n\r\n----------------------------------------------------------------------\r\nFile \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/c/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line 196, in numpy_test\r\nFailed example:\r\n    test_point_record()\r\nExpected:\r\n    array([(0.0, 0.0), (1.0, -1.0), (2.0, -2.0)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\nGot:\r\n    array([( 0.,  0.), ( 1., -1.), ( 2., -2.)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\n\r\n\r\n======================================================================\r\nFAIL: numpy_test (numpy_test.__test__)\r\nDoctest: numpy_test.__test__.numpy_test\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/nix/store/zvm545rqc4d97caqq9h7344bnd06jhzb-python3-3.5.3/lib/python3.5/doctest.py\", line 2190, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_test.__test__.numpy_test\r\n  File \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/c/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line unknown line number, in numpy_test\r\n\r\n----------------------------------------------------------------------\r\nFile \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/c/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line ?, in numpy_test.__test__.numpy_test\r\nFailed example:\r\n    test_point_record()\r\nExpected:\r\n    array([(0.0, 0.0), (1.0, -1.0), (2.0, -2.0)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\nGot:\r\n    array([( 0.,  0.), ( 1., -1.), ( 2., -2.)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\n\r\n\r\n======================================================================\r\nFAIL: numpy_test ()\r\nDoctest: numpy_test\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/nix/store/zvm545rqc4d97caqq9h7344bnd06jhzb-python3-3.5.3/lib/python3.5/doctest.py\", line 2190, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_test\r\n  File \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/cpp/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line 1, in numpy_test\r\n\r\n----------------------------------------------------------------------\r\nFile \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/cpp/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line 196, in numpy_test\r\nFailed example:\r\n    test_point_record()\r\nExpected:\r\n    array([(0.0, 0.0), (1.0, -1.0), (2.0, -2.0)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\nGot:\r\n    array([( 0.,  0.), ( 1., -1.), ( 2., -2.)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\n\r\n\r\n======================================================================\r\nFAIL: numpy_test (numpy_test.__test__)\r\nDoctest: numpy_test.__test__.numpy_test\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/nix/store/zvm545rqc4d97caqq9h7344bnd06jhzb-python3-3.5.3/lib/python3.5/doctest.py\", line 2190, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_test.__test__.numpy_test\r\n  File \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/cpp/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line unknown line number, in numpy_test\r\n\r\n----------------------------------------------------------------------\r\nFile \"/tmp/nix-build-python3.5-Cython-0.25.2.drv-0/Cython-0.25.2/TEST_TMP/run/cpp/numpy_test/numpy_test.cpython-35m-x86_64-linux-gnu.so\", line ?, in numpy_test.__test__.numpy_test\r\nFailed example:\r\n    test_point_record()\r\nExpected:\r\n    array([(0.0, 0.0), (1.0, -1.0), (2.0, -2.0)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\nGot:\r\n    array([( 0.,  0.), ( 1., -1.), ( 2., -2.)], \r\n          dtype=[('x', '!f8'), ('y', '!f8')])\r\n\r\n\r\n----------------------------------------------------------------------\r\nRan 10669 tests in 2126.719s\r\n```",
    "closed_at": null,
    "comment_data": [
        {
            "body": "Seems to be fixed in dd0b10c7e31ea136632bfcfd46c925adcf4c4af6 (but no release yet)",
            "created_at": "2017-05-20T19:29:40Z",
            "html_url": "https://github.com/cython/cython/issues/1676#issuecomment-302893734",
            "id": 302893734,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1676",
            "updated_at": "2017-05-20T19:29:40Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/302893734",
            "user": {
                "avatar_url": "https://avatars1.githubusercontent.com/u/888729?v=3",
                "events_url": "https://api.github.com/users/vbraun/events{/privacy}",
                "followers_url": "https://api.github.com/users/vbraun/followers",
                "following_url": "https://api.github.com/users/vbraun/following{/other_user}",
                "gists_url": "https://api.github.com/users/vbraun/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vbraun",
                "id": 888729,
                "login": "vbraun",
                "organizations_url": "https://api.github.com/users/vbraun/orgs",
                "received_events_url": "https://api.github.com/users/vbraun/received_events",
                "repos_url": "https://api.github.com/users/vbraun/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vbraun/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vbraun/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vbraun"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1676/comments",
    "created_at": "2017-04-17T10:35:53Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/486017?v=3",
                "events_url": "https://api.github.com/users/robertwb/events{/privacy}",
                "followers_url": "https://api.github.com/users/robertwb/followers",
                "following_url": "https://api.github.com/users/robertwb/following{/other_user}",
                "gists_url": "https://api.github.com/users/robertwb/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/robertwb",
                "id": 486017,
                "login": "robertwb",
                "organizations_url": "https://api.github.com/users/robertwb/orgs",
                "received_events_url": "https://api.github.com/users/robertwb/received_events",
                "repos_url": "https://api.github.com/users/robertwb/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/robertwb/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/robertwb/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/robertwb"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-05-21T06:40:14Z",
            "event": "milestoned",
            "id": 1090747480,
            "milestone": {
                "title": "0.26"
            },
            "url": "https://api.github.com/repos/cython/cython/issues/events/1090747480"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1676/events",
    "html_url": "https://github.com/cython/cython/issues/1676",
    "id": 222108017,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1676/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 0,
        "created_at": "2017-05-18T06:47:17Z",
        "creator": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/486017?v=3",
            "events_url": "https://api.github.com/users/robertwb/events{/privacy}",
            "followers_url": "https://api.github.com/users/robertwb/followers",
            "following_url": "https://api.github.com/users/robertwb/following{/other_user}",
            "gists_url": "https://api.github.com/users/robertwb/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/robertwb",
            "id": 486017,
            "login": "robertwb",
            "organizations_url": "https://api.github.com/users/robertwb/orgs",
            "received_events_url": "https://api.github.com/users/robertwb/received_events",
            "repos_url": "https://api.github.com/users/robertwb/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/robertwb/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/robertwb/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/robertwb"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/cython/cython/milestone/44",
        "id": 2528533,
        "labels_url": "https://api.github.com/repos/cython/cython/milestones/44/labels",
        "number": 44,
        "open_issues": 2,
        "state": "open",
        "title": "0.26",
        "updated_at": "2017-05-21T06:40:14Z",
        "url": "https://api.github.com/repos/cython/cython/milestones/44"
    },
    "number": 1676,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Failing numpy_test with numpy 1.12 and 1.12.1",
    "updated_at": "2017-05-21T06:40:13Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1676",
    "user": {
        "avatar_url": "https://avatars0.githubusercontent.com/u/2129135?v=3",
        "events_url": "https://api.github.com/users/FRidh/events{/privacy}",
        "followers_url": "https://api.github.com/users/FRidh/followers",
        "following_url": "https://api.github.com/users/FRidh/following{/other_user}",
        "gists_url": "https://api.github.com/users/FRidh/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/FRidh",
        "id": 2129135,
        "login": "FRidh",
        "organizations_url": "https://api.github.com/users/FRidh/orgs",
        "received_events_url": "https://api.github.com/users/FRidh/received_events",
        "repos_url": "https://api.github.com/users/FRidh/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/FRidh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/FRidh/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/FRidh"
    }
}