{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Testing in two virtual machines, both Xubuntu 17.04 but one 64bit, the other 32bit, the 64bit case works fine but in the 32bit case, cython segfaults when trying to cythonize a .pyx file. This is with python2 in both cases. The backtrace using faulthandler is here:\r\n\r\n[1/1] Cythonizing compizconfig.pyx\r\nFatal Python error: Segmentation fault\r\n\r\nCurrent thread 0xb74e0d00 <python> (most recent call first):\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/ExprNodes.py\", line 657 in allocate_temp_result\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/ExprNodes.py\", line 703 in generate_evaluation_code\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py\", line 5895 in generate_execution_code\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py\", line 5857 in generate_execution_code\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py\", line 442 in generate_execution_code\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py\", line 1699 in generate_function_body\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py\", line 1932 in generate_function_definitions\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py\", line 436 in generate_function_definitions\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py\", line 436 in generate_function_definitions\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/ModuleNode.py\", line 365 in generate_c_code\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/ModuleNode.py\", line 137 in process_implementation\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Pipeline.py\", line 53 in generate_pyx_code_stage\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Pipeline.py\", line 340 in run_pipeline\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py\", line 494 in run_pipeline\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py\", line 664 in compile_multiple\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py\", line 686 in compile\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py\", line 1039 in cythonize_one\r\n  File \"/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py\", line 934 in cythonize\r\n  File \"<stdin>\", line 1 in <module>\r\nSegmentation fault\r\n\r\nTo reproduce this, I am using [this file](https://github.com/compiz-reloaded/compizconfig-python/blob/master/src/compizconfig.pyx) and running python to get to a prompt, then:\r\n\r\n&gt;&gt;&gt; import faulthandler\r\n&gt;&gt;&gt; faulthandler.enable()\r\n&gt;&gt;&gt; from Cython.Build import cythonize\r\n&gt;&gt;&gt; cythonize(\"compizconfig.pyx\")",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1854/comments",
    "created_at": "2017-08-31T23:24:49Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1854/events",
    "html_url": "https://github.com/cython/cython/issues/1854",
    "id": 254495780,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1854/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1854,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Cython crash on 32bit",
    "updated_at": "2017-08-31T23:36:19Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1854",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/1450125?v=4",
        "events_url": "https://api.github.com/users/soreau/events{/privacy}",
        "followers_url": "https://api.github.com/users/soreau/followers",
        "following_url": "https://api.github.com/users/soreau/following{/other_user}",
        "gists_url": "https://api.github.com/users/soreau/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/soreau",
        "id": 1450125,
        "login": "soreau",
        "organizations_url": "https://api.github.com/users/soreau/orgs",
        "received_events_url": "https://api.github.com/users/soreau/received_events",
        "repos_url": "https://api.github.com/users/soreau/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/soreau/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/soreau/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/soreau"
    }
}