{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Quite possibly a derp on my part, but should still have a better exception name if it is.\r\n\r\nThe error:\r\n\r\n```\r\nE:\\vulkan>call \"E:\\Visual Studio 2017 Community\\VC\\Auxiliary\\Build\\vcvars64.bat\"\r\n**********************************************************************\r\n** Visual Studio 2017 Developer Command Prompt v15.0.26730.16\r\n** Copyright (c) 2017 Microsoft Corporation\r\n**********************************************************************\r\n[vcvarsall.bat] Environment initialized for: 'x64'\r\nC:\\Program Files\\Python36\\lib\\distutils\\dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'\r\n  warnings.warn(msg)\r\nC:\\Program Files\\Python36\\lib\\distutils\\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'\r\n  warnings.warn(msg)\r\nC:\\Program Files\\Python36\\lib\\distutils\\dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'\r\n  warnings.warn(msg)\r\nrunning build_ext\r\ncythoning vulkan.__init__.pyx to vulkan.__init__.c\r\nTraceback (most recent call last):\r\n  File \"cython_setup.py\", line 37, in <module>\r\n    \"Topic :: Software Development :: Libraries :: Python Modules\",\r\n  File \"C:\\Program Files\\Python36\\lib\\distutils\\core.py\", line 148, in setup\r\n    dist.run_commands()\r\n  File \"C:\\Program Files\\Python36\\lib\\distutils\\dist.py\", line 955, in run_commands\r\n    self.run_command(cmd)\r\n  File \"C:\\Program Files\\Python36\\lib\\distutils\\dist.py\", line 974, in run_command\r\n    cmd_obj.run()\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Distutils\\old_build_ext.py\", line 186, in run\r\n    _build_ext.build_ext.run(self)\r\n  File \"C:\\Program Files\\Python36\\lib\\distutils\\command\\build_ext.py\", line 339, in run\r\n    self.build_extensions()\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Distutils\\old_build_ext.py\", line 193, in build_extensions\r\n    ext.sources = self.cython_sources(ext.sources, ext)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Distutils\\old_build_ext.py\", line 346, in cython_sources\r\n    full_module_name=module_name)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Main.py\", line 693, in compile\r\n    return compile_single(source, options, full_module_name)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Main.py\", line 643, in compile_single\r\n    return run_pipeline(source, options, full_module_name)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Main.py\", line 494, in run_pipeline\r\n    err, enddata = Pipeline.run_pipeline(pipeline, source)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Pipeline.py\", line 354, in run_pipeline\r\n    data = run(phase, data)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Pipeline.py\", line 334, in run\r\n    return phase(data)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Pipeline.py\", line 32, in parse\r\n    scope = context.find_module(full_module_name, pos = initial_pos, need_pxd = 0)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Main.py\", line 188, in find_module\r\n    scope = scope.find_submodule(name)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Main.py\", line 337, in find_submodule\r\n    parent_module = None, context = self)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\Cython\\Compiler\\Symtab.py\", line 1099, in __init__\r\n    self.module_name = parent_module.module_name\r\nAttributeError: 'NoneType' object has no attribute 'module_name'\r\n```\r\n\r\nI had a module like this:\r\n\r\n```\r\next_modules = [Extension(\"__init__\",\r\n                         [\"vulkan.__init__.pyx\"],\r\n                         )]\r\n```\r\n\r\nfixed by changing to\r\n\r\n```\r\next_modules = [Extension(\"vulkan\",\r\n                         [\"vulkan.pyx\"],\r\n                         )]\r\n```\r\n\r\nand moving the file accordingly.\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "OWNER",
            "body": "Shouldn't it be `vulkan\\__init__.pyx` ?",
            "created_at": "2017-10-03T18:33:32Z",
            "html_url": "https://github.com/cython/cython/issues/1904#issuecomment-333937295",
            "id": 333937295,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1904",
            "updated_at": "2017-10-03T18:33:32Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/333937295",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "Well, yes, but I changed that to just be vulkan. But that then turned out to not work (but more due to how the vulkan package works, as opposed to cython.)\r\nAnyway, My current problem is even different to that but seems to be a cython issue:\r\n\r\nThe command is now:\r\n\r\n`ext_modules = cythonize(\"vulkan/*.pyx\")`\r\n\r\n```\r\n[vcvarsall.bat] Environment initialized for: 'x64'\r\nC:\\Program Files\\Python36\\lib\\distutils\\dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'\r\n  warnings.warn(msg)\r\nC:\\Program Files\\Python36\\lib\\distutils\\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'\r\n  warnings.warn(msg)\r\nC:\\Program Files\\Python36\\lib\\distutils\\dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'\r\n  warnings.warn(msg)\r\nrunning build_ext\r\nbuilding 'vulkan.__init__' extension\r\nE:\\Visual Studio 2017 Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD \"-IE:\\Visual Studio 2017 Community\\VC\\Redist\\MSVC\\14.10.25017\\onecore\\x64\\Microsoft.VC150.CRT\" \"-IC:\\Program Files\\Python36\\include\" \"-IC:\\Program Files\\Python36\\include\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.15063.0\\ucrt\" \"-IC:\\Program Files (x86)\\Visual C++ BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\include\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.15063.0\\shared\" /Tcvulkan\\__init__.c /Fobuild\\temp.win-amd64-3.6\\Release\\vulkan\\__init__.obj\r\n__init__.c\r\nE:\\Visual Studio 2017 Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO \"/LIBPATH:C:\\Program Files\\Python36\\libs\" \"/LIBPATH:C:\\Program Files\\Python36\\PCbuild\\amd64\" \"/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.15063.0\\ucrt\\x64\" \"/LIBPATH:E:\\Visual Studio 2017 Community\\VC\\Tools\\MSVC\\14.11.25503\\lib\\x64\" \"/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.15063.0\\um\\x64\" /EXPORT:PyInit___init__ build\\temp.win-amd64-3.6\\Release\\vulkan\\__init__.obj /OUT:E:\\vulkan\\vulkan\\__init__.cp36-win_amd64.pyd /IMPLIB:build\\temp.win-amd64-3.6\\Release\\vulkan\\__init__.cp36-win_amd64.lib\r\nLINK : error LNK2001: unresolved external symbol PyInit___init__\r\nbuild\\temp.win-amd64-3.6\\Release\\vulkan\\__init__.cp36-win_amd64.lib : fatal error LNK1120: 1 unresolved externals\r\nerror: command 'E:\\\\Visual Studio 2017 Community\\\\VC\\\\Tools\\\\MSVC\\\\14.11.25503\\\\bin\\\\HostX64\\\\x64\\\\link.exe' failed with exit status 1120\r\n```\r\n\r\nGoogline for that link error tells me that plenty of people in the past had problems cythoning various `__init__ `files.\r\n",
            "created_at": "2017-10-03T21:05:57Z",
            "html_url": "https://github.com/cython/cython/issues/1904#issuecomment-333978529",
            "id": 333978529,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1904",
            "updated_at": "2017-10-03T21:07:58Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/333978529",
            "user": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/3189725?v=4",
                "events_url": "https://api.github.com/users/Berserker66/events{/privacy}",
                "followers_url": "https://api.github.com/users/Berserker66/followers",
                "following_url": "https://api.github.com/users/Berserker66/following{/other_user}",
                "gists_url": "https://api.github.com/users/Berserker66/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Berserker66",
                "id": 3189725,
                "login": "Berserker66",
                "organizations_url": "https://api.github.com/users/Berserker66/orgs",
                "received_events_url": "https://api.github.com/users/Berserker66/received_events",
                "repos_url": "https://api.github.com/users/Berserker66/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Berserker66/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Berserker66/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Berserker66"
            }
        },
        {
            "author_association": "OWNER",
            "body": "Yes, it's not really portable. Things improved in recent CPython versions, but the easiest way is probably still to use an \"__init__.py\" file and from-import your extension in it, so that the names get forwarded.\n",
            "created_at": "2017-10-04T04:38:47Z",
            "html_url": "https://github.com/cython/cython/issues/1904#issuecomment-334047866",
            "id": 334047866,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1904",
            "updated_at": "2017-10-04T04:38:47Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/334047866",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1904/comments",
    "created_at": "2017-10-02T17:45:44Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1904/events",
    "html_url": "https://github.com/cython/cython/issues/1904",
    "id": 262166923,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1904/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1904,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "AttributeError: 'NoneType' object has no attribute 'module_name' in SymTab.py",
    "updated_at": "2017-10-04T04:38:47Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1904",
    "user": {
        "avatar_url": "https://avatars2.githubusercontent.com/u/3189725?v=4",
        "events_url": "https://api.github.com/users/Berserker66/events{/privacy}",
        "followers_url": "https://api.github.com/users/Berserker66/followers",
        "following_url": "https://api.github.com/users/Berserker66/following{/other_user}",
        "gists_url": "https://api.github.com/users/Berserker66/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/Berserker66",
        "id": 3189725,
        "login": "Berserker66",
        "organizations_url": "https://api.github.com/users/Berserker66/orgs",
        "received_events_url": "https://api.github.com/users/Berserker66/received_events",
        "repos_url": "https://api.github.com/users/Berserker66/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/Berserker66/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Berserker66/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/Berserker66"
    }
}