{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "When doing a Pip install of cython, it failed while running gcc with error `unrecognized command line option ‘-fstack-protector-strong’`. Googling this suggests that gcc >= v4.9 is necessary to use this flag. Is this really a hard requirement? Is there any way to make this work with gcc v4.7?\r\n\r\nOne thing that is confusing me is that I tried installing cython v0.18, which was released before the release of gcc v4.9 and it still had this same error. So is it actually some unrelated issue?",
    "closed_at": "2017-10-31T07:16:20Z",
    "comment_data": [
        {
            "author_association": "OWNER",
            "body": "Cython does not enforce any specific CFLAGS. Maybe they come in through your Python setup, or via environment variables?\n",
            "created_at": "2017-10-30T09:11:17Z",
            "html_url": "https://github.com/cython/cython/issues/1967#issuecomment-340384546",
            "id": 340384546,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1967",
            "updated_at": "2017-10-30T09:11:17Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/340384546",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "Thanks for the quick response. It seems that CFLAGS is not defined on this system:\r\n```Python 2.7.5 (default, Nov  6 2016, 00:28:07)\r\n[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import os\r\n>>> print os.environ['CFLAGS']\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/bmishkania/bin/localPython/lib64/python2.7/UserDict.py\", line 23, in __getitem__\r\n    raise KeyError(key)\r\nKeyError: 'CFLAGS'\r\n```\r\n\r\nI even tried setting CFLAGS=\"\" when doing the pip install and it had the same error. Do you have an idea of where these flags may be coming from?",
            "created_at": "2017-10-30T16:42:56Z",
            "html_url": "https://github.com/cython/cython/issues/1967#issuecomment-340506164",
            "id": 340506164,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1967",
            "updated_at": "2017-10-30T16:42:56Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/340506164",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/6743930?v=4",
                "events_url": "https://api.github.com/users/benmishkanian/events{/privacy}",
                "followers_url": "https://api.github.com/users/benmishkanian/followers",
                "following_url": "https://api.github.com/users/benmishkanian/following{/other_user}",
                "gists_url": "https://api.github.com/users/benmishkanian/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/benmishkanian",
                "id": 6743930,
                "login": "benmishkanian",
                "organizations_url": "https://api.github.com/users/benmishkanian/orgs",
                "received_events_url": "https://api.github.com/users/benmishkanian/received_events",
                "repos_url": "https://api.github.com/users/benmishkanian/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/benmishkanian/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/benmishkanian/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/benmishkanian"
            }
        },
        {
            "author_association": "OWNER",
            "body": "Probably from the C compiler flags that were used to build your CPython installation.\r\nIn any case, this is not a Cython issue, so I'll close this ticket. For support questions, please contact the cython-users mailing list instead of opening tickets on the bug tracker.",
            "created_at": "2017-10-31T07:16:20Z",
            "html_url": "https://github.com/cython/cython/issues/1967#issuecomment-340679591",
            "id": 340679591,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1967",
            "updated_at": "2017-10-31T07:16:20Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/340679591",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1967/comments",
    "created_at": "2017-10-30T01:17:58Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-10-31T07:15:22Z",
            "event": "labeled",
            "id": 1318166121,
            "label": {
                "color": "444444",
                "name": "R: invalid"
            },
            "url": "https://api.github.com/repos/cython/cython/issues/events/1318166121"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-10-31T07:15:22Z",
            "event": "labeled",
            "id": 1318166122,
            "label": {
                "color": "fef2c0",
                "name": "support question"
            },
            "url": "https://api.github.com/repos/cython/cython/issues/events/1318166122"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-10-31T07:16:20Z",
            "event": "closed",
            "id": 1318167161,
            "url": "https://api.github.com/repos/cython/cython/issues/events/1318167161"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1967/events",
    "html_url": "https://github.com/cython/cython/issues/1967",
    "id": 269456439,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "id": 425557122,
            "name": "R: invalid",
            "url": "https://api.github.com/repos/cython/cython/labels/R:%20invalid"
        },
        {
            "color": "fef2c0",
            "default": false,
            "id": 414800623,
            "name": "support question",
            "url": "https://api.github.com/repos/cython/cython/labels/support%20question"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1967/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1967,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "Pip install fails with error unrecognized command line option ‘-fstack-protector-strong’",
    "updated_at": "2017-10-31T07:16:20Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1967",
    "user": {
        "avatar_url": "https://avatars3.githubusercontent.com/u/6743930?v=4",
        "events_url": "https://api.github.com/users/benmishkanian/events{/privacy}",
        "followers_url": "https://api.github.com/users/benmishkanian/followers",
        "following_url": "https://api.github.com/users/benmishkanian/following{/other_user}",
        "gists_url": "https://api.github.com/users/benmishkanian/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/benmishkanian",
        "id": 6743930,
        "login": "benmishkanian",
        "organizations_url": "https://api.github.com/users/benmishkanian/orgs",
        "received_events_url": "https://api.github.com/users/benmishkanian/received_events",
        "repos_url": "https://api.github.com/users/benmishkanian/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/benmishkanian/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/benmishkanian/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/benmishkanian"
    }
}