{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Cython**: 0.28a0 (built from source, master branch, no modifications, commit: 177dbe83d5c7551cb2cad790cb5a963b54cf19ef)\r\n**Python**: 3.6.3\r\n\r\nSteps to reproduce:\r\n\r\nFile `foo.pyx`:\r\n\r\n```python\r\nasync def bar(loop):\r\n    fut = loop.create_future()\r\n    loop.call_later(1, lambda: fut.set_result(1))\r\n    await fut\r\n\r\nasync def foo(loop):\r\n    await bar(loop)\r\n```\r\n\r\nFile `test_foo.py`:\r\n\r\n```cython\r\nimport asyncio\r\nimport pyximport; pyximport.install()\r\n\r\nimport foo\r\n\r\n\r\nasync def call():\r\n    await foo.foo(loop)\r\n\r\nloop = asyncio.get_event_loop()\r\nloop.run_until_complete(call())\r\n```\r\n\r\nRun:\r\n\r\n```\r\n» python test_foo.py\r\nfish: “python test_foo.py” terminated by signal SIGSEGV (Address boundary error)\r\n```\r\n\r\nLLDB output:\r\n\r\n```\r\n» lldb -- python test_foo.py\r\n(lldb) target create \"python\"\r\nCurrent executable set to 'python' (x86_64).\r\n(lldb) settings set -- target.run-args  \"test_foo.py\"\r\n(lldb) run\r\nProcess 72096 launched: '/Users/yury/dev/venvs/uvloop/bin/python' (x86_64)\r\nProcess 72096 stopped\r\n* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)\r\n    frame #0: 0x0000000000000000\r\nerror: memory read failed for 0x0\r\nTarget 0: (python) stopped.\r\n(lldb) up\r\nfoo.cpython-36m-darwin.so was compiled with optimization - stepping may behave oddly; variables may not be available.\r\nframe #1: 0x00000001047ec19b foo.cpython-36m-darwin.so`__Pyx_Generator_Next(self=0x00000001044634c8) at foo.c:3823 [opt]\r\n   3820\t            ret = _PyGen_Send((PyGenObject*)yf, NULL);\r\n   3821\t        } else\r\n   3822\t        #endif\r\n-> 3823\t            ret = Py_TYPE(yf)->tp_iternext(yf);\r\n   3824\t        gen->is_running = 0;\r\n   3825\t        if (likely(ret)) {\r\n   3826\t            return ret;\r\n```",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "Bug is reproducible on Cython 0.27.3 too.",
            "created_at": "2017-11-14T20:57:41Z",
            "html_url": "https://github.com/cython/cython/issues/1999#issuecomment-344396007",
            "id": 344396007,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1999",
            "updated_at": "2017-11-14T20:57:41Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/344396007",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/239003?v=4",
                "events_url": "https://api.github.com/users/1st1/events{/privacy}",
                "followers_url": "https://api.github.com/users/1st1/followers",
                "following_url": "https://api.github.com/users/1st1/following{/other_user}",
                "gists_url": "https://api.github.com/users/1st1/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/1st1",
                "id": 239003,
                "login": "1st1",
                "organizations_url": "https://api.github.com/users/1st1/orgs",
                "received_events_url": "https://api.github.com/users/1st1/received_events",
                "repos_url": "https://api.github.com/users/1st1/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/1st1/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/1st1/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/1st1"
            }
        },
        {
            "author_association": "NONE",
            "body": "This fixes the problem for me:\r\n\r\n```diff\r\ndiff --git a/Cython/Utility/Coroutine.c b/Cython/Utility/Coroutine.c\r\nindex ad273d286..b65bcd6ad 100644\r\n--- a/Cython/Utility/Coroutine.c\r\n+++ b/Cython/Utility/Coroutine.c\r\n@@ -893,6 +893,11 @@ static PyObject *__Pyx_Generator_Next(PyObject *self) {\r\n         if (PyGen_CheckExact(yf)) {\r\n             ret = _PyGen_Send((PyGenObject*)yf, NULL);\r\n         } else\r\n+        #endif\r\n+        #ifdef __Pyx_Coroutine_USED\r\n+        if (__Pyx_Coroutine_Check(yf)) {\r\n+            ret = __Pyx_Coroutine_Send(yf, Py_None);\r\n+        } else\r\n         #endif\r\n             ret = Py_TYPE(yf)->tp_iternext(yf);\r\n         gen->is_running = 0;\r\n```",
            "created_at": "2017-11-14T21:54:00Z",
            "html_url": "https://github.com/cython/cython/issues/1999#issuecomment-344411786",
            "id": 344411786,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1999",
            "updated_at": "2017-11-14T21:54:00Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/344411786",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/239003?v=4",
                "events_url": "https://api.github.com/users/1st1/events{/privacy}",
                "followers_url": "https://api.github.com/users/1st1/followers",
                "following_url": "https://api.github.com/users/1st1/following{/other_user}",
                "gists_url": "https://api.github.com/users/1st1/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/1st1",
                "id": 239003,
                "login": "1st1",
                "organizations_url": "https://api.github.com/users/1st1/orgs",
                "received_events_url": "https://api.github.com/users/1st1/received_events",
                "repos_url": "https://api.github.com/users/1st1/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/1st1/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/1st1/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/1st1"
            }
        }
    ],
    "comments": 2,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1999/comments",
    "created_at": "2017-11-14T20:56:00Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1999/events",
    "html_url": "https://github.com/cython/cython/issues/1999",
    "id": 273939630,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1999/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1999,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "segfault in simple async/await code",
    "updated_at": "2017-11-14T21:54:00Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1999",
    "user": {
        "avatar_url": "https://avatars0.githubusercontent.com/u/239003?v=4",
        "events_url": "https://api.github.com/users/1st1/events{/privacy}",
        "followers_url": "https://api.github.com/users/1st1/followers",
        "following_url": "https://api.github.com/users/1st1/following{/other_user}",
        "gists_url": "https://api.github.com/users/1st1/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/1st1",
        "id": 239003,
        "login": "1st1",
        "organizations_url": "https://api.github.com/users/1st1/orgs",
        "received_events_url": "https://api.github.com/users/1st1/received_events",
        "repos_url": "https://api.github.com/users/1st1/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/1st1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/1st1/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/1st1"
    }
}