{
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "[Cython's documentation](http://docs.cython.org/en/latest/src/userguide/sharing_declarations.html#search-paths-for-definition-files) claims that `cimport` searches for `pxd` files also in Python's `sys.path`.  That doesn't seem to be true for a package that is installed in `$HOME/.local/lib/pythonX.X/site-packages`, a location that is added to Python's `sys.path` since PEP 370.\r\n\r\nHere's a demonstration of the problem that works with Cython 0.28.4.\r\n\r\nLet's create a trivial Python package and also make it cimportable:\r\n\r\n```\r\nmkdir -p ~/.local/lib/python3.6/site-packages/package\r\ncd ~/.local/lib/python3.6/site-packages/package\r\ntouch __init__.py\r\ntouch __init__.pxd\r\n```\r\n\r\nNow, creating somewhere else the file `test.pyx` with the contents\r\n\r\n```\r\ncimport package\r\n```\r\n\r\nand compiling it with `cython --embed -3 test.pyx` fails with the error message\r\n\r\n```\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\ncimport package\r\n       ^\r\n------------------------------------------------------------\r\n\r\ntest.pyx:1:8: 'package.pxd' not found\r\n```\r\n\r\nAdding the directory `$HOME/.local/lib/python3.6/site-packages` to `$PYTHONPATH` works around the problem, but shouldn't Cython include that directory already by itself?\r\n",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2525/comments",
    "created_at": "2018-07-30T16:29:57Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2525/events",
    "html_url": "https://github.com/cython/cython/issues/2525",
    "id": 345834646,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2525/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzNDU4MzQ2NDY=",
    "number": 2525,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "cimport does not search in `$HOME/.local/`",
    "updated_at": "2018-07-30T16:29:57Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2525",
    "user": {
        "avatar_url": "https://avatars0.githubusercontent.com/u/2375954?v=4",
        "events_url": "https://api.github.com/users/grothesque/events{/privacy}",
        "followers_url": "https://api.github.com/users/grothesque/followers",
        "following_url": "https://api.github.com/users/grothesque/following{/other_user}",
        "gists_url": "https://api.github.com/users/grothesque/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/grothesque",
        "id": 2375954,
        "login": "grothesque",
        "node_id": "MDQ6VXNlcjIzNzU5NTQ=",
        "organizations_url": "https://api.github.com/users/grothesque/orgs",
        "received_events_url": "https://api.github.com/users/grothesque/received_events",
        "repos_url": "https://api.github.com/users/grothesque/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/grothesque/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/grothesque/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/grothesque"
    }
}