{
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "I think this is the same issue: https://grokbase.com/t/gg/cython-users/1417hszq2d/pxd-import-problem-when-modules-added-to-package\r\n\r\nI have code in a .pyx file in my package PDSim (https://github.com/ibell/pdsim) that reads:\r\n```\r\nfrom PDSim.flow cimport flow_models\r\n```\r\nwhich yields the error (though somehow not terminal):\r\n```\r\nPDSim/scroll/_scroll.pyx: cannot find cimported module 'PDSim.flow'\r\n```\r\nin which the folder flow in my package has the contents:\r\n```\r\n>> ls -l\r\n-rw-rw-r-- 1 ian ian  2216 Dec 19  2017 fanno.pyx\r\n-rw-rw-r-- 1 ian ian  1933 Dec 19  2017 flow_models.pxd\r\n-rw-rw-r-- 1 ian ian 24767 Sep 30 18:32 flow_models.pyx\r\n-rw-rw-r-- 1 ian ian  2407 Dec 19  2017 flow.pxd\r\n-rw-rw-r-- 1 ian ian 13527 Dec 19  2017 flow.pyx\r\n-rw-rw-r-- 1 ian ian     0 Dec 19  2017 __init__.py\r\n```\r\n\r\n\r\nWhy does it not find this module?  ",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "I can \"fix\" the issue with the replacement of\r\n```\r\nfrom PDSim.flow cimport flow_models\r\n```\r\nby\r\n```\r\ncimport PDSim.flow.flow_models as flow_models\r\n```\r\nwhich is pretty verbose, and smells like a bug.  The parallel python import is\r\n```\r\nfrom PDSim.flow import flow_models\r\n```\r\nwhich works fine.\r\n",
            "created_at": "2018-10-01T18:41:31Z",
            "html_url": "https://github.com/cython/cython/issues/2638#issuecomment-426017536",
            "id": 426017536,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2638",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQyNjAxNzUzNg==",
            "updated_at": "2018-10-01T18:41:31Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/426017536",
            "user": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/1859947?v=4",
                "events_url": "https://api.github.com/users/ibell/events{/privacy}",
                "followers_url": "https://api.github.com/users/ibell/followers",
                "following_url": "https://api.github.com/users/ibell/following{/other_user}",
                "gists_url": "https://api.github.com/users/ibell/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ibell",
                "id": 1859947,
                "login": "ibell",
                "node_id": "MDQ6VXNlcjE4NTk5NDc=",
                "organizations_url": "https://api.github.com/users/ibell/orgs",
                "received_events_url": "https://api.github.com/users/ibell/received_events",
                "repos_url": "https://api.github.com/users/ibell/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ibell/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ibell/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ibell"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2638/comments",
    "created_at": "2018-10-01T17:47:04Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2638/events",
    "html_url": "https://github.com/cython/cython/issues/2638",
    "id": 365570777,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2638/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzNjU1NzA3Nzc=",
    "number": 2638,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Bug in absolute import handling in python 2.7",
    "updated_at": "2018-10-01T18:41:31Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2638",
    "user": {
        "avatar_url": "https://avatars2.githubusercontent.com/u/1859947?v=4",
        "events_url": "https://api.github.com/users/ibell/events{/privacy}",
        "followers_url": "https://api.github.com/users/ibell/followers",
        "following_url": "https://api.github.com/users/ibell/following{/other_user}",
        "gists_url": "https://api.github.com/users/ibell/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/ibell",
        "id": 1859947,
        "login": "ibell",
        "node_id": "MDQ6VXNlcjE4NTk5NDc=",
        "organizations_url": "https://api.github.com/users/ibell/orgs",
        "received_events_url": "https://api.github.com/users/ibell/received_events",
        "repos_url": "https://api.github.com/users/ibell/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/ibell/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ibell/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/ibell"
    }
}