$ python runtests.py
Python 2.7.3 (default, Apr 18 2012, 21:11:11) 
[GCC 4.2.1 Compatible Apple Clang 3.1 (tags/Apple/clang-318.0.45)]

Running tests against Cython 0.17pre 5fcc3e2e051e04fea2cf6d07cd0de94c1e11dca8
Backends: c,cpp

In file included from BUILD/inline/_cython_inline_5226c9d314121a355925a1add4832afe.c:275:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:14:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:1: warning: unused
      function '_import_array' [-Wunused-function]
_import_array(void)
^
In file included from BUILD/inline/_cython_inline_5226c9d314121a355925a1add4832afe.c:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
2 warnings generated.
Compiling /Users/deil/.cython/inline/_cython_inline_6fb930a52af85bda80af010da3ebe16b.pyx because it changed.
Cythonizing /Users/deil/.cython/inline/_cython_inline_6fb930a52af85bda80af010da3ebe16b.pyx
/Users/deil/code/cython/Cython/Debugger/Tests/TestLibCython.py:74: UserWarning: Skipping gdb tests, need gdb >= 7.2 with Python >= 2.6
  'Skipping gdb tests, need gdb >= 7.2 with Python >= 2.6')
cythonscope.c:18033:12: warning: unused function '__Pyx_ValidateAndInit_memviewslice' [-Wunused-function]
static int __Pyx_ValidateAndInit_memviewslice(
           ^
1 warning generated.
cythonscope.cpp:18033:12: warning: unused function '__Pyx_ValidateAndInit_memviewslice' [-Wunused-function]
static int __Pyx_ValidateAndInit_memviewslice(
           ^
1 warning generated.
directive_locals_in_pxd.c:583:17: warning: explicitly assigning a variable of type 'double' to itself [-Wself-assign]
    __pyx_v_egg = __pyx_v_egg;
    ~~~~~~~~~~~ ^ ~~~~~~~~~~~
directive_locals_in_pxd.c:659:17: warning: explicitly assigning a variable of type 'double' to itself [-Wself-assign]
    __pyx_v_egg = __pyx_v_egg;
    ~~~~~~~~~~~ ^ ~~~~~~~~~~~
2 warnings generated.
directive_locals_in_pxd.cpp:583:17: warning: explicitly assigning a variable of type 'double' to itself [-Wself-assign]
    __pyx_v_egg = __pyx_v_egg;
    ~~~~~~~~~~~ ^ ~~~~~~~~~~~
directive_locals_in_pxd.cpp:659:17: warning: explicitly assigning a variable of type 'double' to itself [-Wself-assign]
    __pyx_v_egg = __pyx_v_egg;
    ~~~~~~~~~~~ ^ ~~~~~~~~~~~
2 warnings generated.
extended_unpacking_T235.c:1551:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:1837:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_7 = __pyx_t_7;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:1965:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:2251:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_7 = __pyx_t_7;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:2422:15: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
    __pyx_t_8 = __pyx_t_8;
    ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:2666:16: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
    __pyx_t_10 = __pyx_t_10;
    ~~~~~~~~~~ ^ ~~~~~~~~~~
extended_unpacking_T235.c:2801:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:2954:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:3423:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:3542:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:3661:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:3803:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:3958:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:4113:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.c:4305:14: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_13 = __pyx_t_13;
  ~~~~~~~~~~ ^ ~~~~~~~~~~
extended_unpacking_T235.c:4766:14: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_12 = __pyx_t_12;
  ~~~~~~~~~~ ^ ~~~~~~~~~~
extended_unpacking_T235.c:5039:16: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
    __pyx_t_14 = __pyx_t_14;
    ~~~~~~~~~~ ^ ~~~~~~~~~~
17 warnings generated.
extended_unpacking_T235.cpp:1551:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:1837:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_7 = __pyx_t_7;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:1965:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:2251:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_7 = __pyx_t_7;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:2422:15: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
    __pyx_t_8 = __pyx_t_8;
    ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:2666:16: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
    __pyx_t_10 = __pyx_t_10;
    ~~~~~~~~~~ ^ ~~~~~~~~~~
extended_unpacking_T235.cpp:2801:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:2954:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:3423:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:3542:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:3661:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_4 = __pyx_t_4;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:3803:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:3958:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:4113:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
extended_unpacking_T235.cpp:4305:14: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_13 = __pyx_t_13;
  ~~~~~~~~~~ ^ ~~~~~~~~~~
extended_unpacking_T235.cpp:4766:14: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_12 = __pyx_t_12;
  ~~~~~~~~~~ ^ ~~~~~~~~~~
extended_unpacking_T235.cpp:5039:16: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
    __pyx_t_14 = __pyx_t_14;
    ~~~~~~~~~~ ^ ~~~~~~~~~~
17 warnings generated.
fused_def.c:30478:18: warning: unused function '__Pyx_Method_ClassMethod' [-Wunused-function]
static PyObject* __Pyx_Method_ClassMethod(PyObject *method) {
                 ^
1 warning generated.
fused_def.cpp:30478:18: warning: unused function '__Pyx_Method_ClassMethod' [-Wunused-function]
static PyObject* __Pyx_Method_ClassMethod(PyObject *method) {
                 ^
1 warning generated.
memoryview.c:8381:11: warning: explicitly assigning a variable of type '__Pyx_memviewslice' to itself [-Wself-assign]
  __pyx_r = __pyx_r;
  ~~~~~~~ ^ ~~~~~~~
memoryview.c:8439:11: warning: explicitly assigning a variable of type '__Pyx_memviewslice' to itself [-Wself-assign]
  __pyx_r = __pyx_r;
  ~~~~~~~ ^ ~~~~~~~
memoryview.c:9617:11: warning: explicitly assigning a variable of type '__Pyx_memviewslice' to itself [-Wself-assign]
  __pyx_r = __pyx_r;
  ~~~~~~~ ^ ~~~~~~~
3 warnings generated.
memoryviewattrs.c:3828:25: warning: expression result unused [-Wunused-value]
  __pyx_v_uninitialized.data;
  ~~~~~~~~~~~~~~~~~~~~~ ^~~~
In file included from memoryviewattrs.c:275:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:14:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:1: warning: unused
      function '_import_array' [-Wunused-function]
_import_array(void)
^
In file included from memoryviewattrs.c:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
3 warnings generated.
memoryviewattrs.cpp:3828:25: warning: expression result unused [-Wunused-value]
  __pyx_v_uninitialized.data;
  ~~~~~~~~~~~~~~~~~~~~~ ^~~~
In file included from memoryviewattrs.cpp:275:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:14:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:1: warning: unused
      function '_import_array' [-Wunused-function]
_import_array(void)
^
In file included from memoryviewattrs.cpp:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
3 warnings generated.
acquired default
acquired Global_A
acquired default
acquired Global_A
In file included from numpy_bufacc_T155.c:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
1 warning generated.
In file included from numpy_bufacc_T155.cpp:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
1 warning generated.
In file included from numpy_cimport.c:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
numpy_cimport.c:953:12: warning: unused function '__pyx_pw_5numpy_7ndarray_1__getbuffer__' [-Wunused-function]
static int __pyx_pw_5numpy_7ndarray_1__getbuffer__(PyObject *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags) {
           ^
numpy_cimport.c:1859:13: warning: unused function '__pyx_pw_5numpy_7ndarray_3__releasebuffer__' [-Wunused-function]
static void __pyx_pw_5numpy_7ndarray_3__releasebuffer__(PyObject *__pyx_v_self, Py_buffer *__pyx_v_info) {
            ^
3 warnings generated.
In file included from numpy_cimport.cpp:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
numpy_cimport.cpp:953:12: warning: unused function '__pyx_pw_5numpy_7ndarray_1__getbuffer__' [-Wunused-function]
static int __pyx_pw_5numpy_7ndarray_1__getbuffer__(PyObject *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags) {
           ^
numpy_cimport.cpp:1859:13: warning: unused function '__pyx_pw_5numpy_7ndarray_3__releasebuffer__' [-Wunused-function]
static void __pyx_pw_5numpy_7ndarray_3__releasebuffer__(PyObject *__pyx_v_self, Py_buffer *__pyx_v_info) {
            ^
3 warnings generated.
In file included from numpy_memoryview.c:275:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:14:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:1: warning: unused
      function '_import_array' [-Wunused-function]
_import_array(void)
^
In file included from numpy_memoryview.c:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
2 warnings generated.
In file included from numpy_memoryview.cpp:275:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:14:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:1: warning: unused
      function '_import_array' [-Wunused-function]
_import_array(void)
^
In file included from numpy_memoryview.cpp:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
2 warnings generated.
In file included from numpy_test.c:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
1 warning generated.
In file included from numpy_test.cpp:276:
In file included from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:152:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: unused function
      '_import_umath' [-Wunused-function]
_import_umath(void)
^
1 warning generated.
pointers.c:861:45: warning: self-comparison always evaluates to true [-Wtautological-compare]
    __pyx_t_2 = (__pyx_v_8pointers_c_string == __pyx_v_8pointers_c_string);
                                            ^
pointers.c:975:49: warning: self-comparison always evaluates to true [-Wtautological-compare]
        __pyx_t_1 = (__pyx_v_8pointers_c_string == __pyx_v_8pointers_c_string);
                                                ^
2 warnings generated.
pointers.cpp:861:45: warning: self-comparison always evaluates to true [-Wtautological-compare]
    __pyx_t_2 = (__pyx_v_8pointers_c_string == __pyx_v_8pointers_c_string);
                                            ^
pointers.cpp:975:49: warning: self-comparison always evaluates to true [-Wtautological-compare]
        __pyx_t_1 = (__pyx_v_8pointers_c_string == __pyx_v_8pointers_c_string);
                                                ^
2 warnings generated.
python_bool_type.c:3790:26: warning: self-comparison always evaluates to true [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x == __pyx_v_x);
                         ^
python_bool_type.c:3816:26: warning: self-comparison always evaluates to false [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x != __pyx_v_x);
                         ^
python_bool_type.c:3962:26: warning: self-comparison always evaluates to true [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x == __pyx_v_x);
                         ^
python_bool_type.c:3988:26: warning: self-comparison always evaluates to false [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x != __pyx_v_x);
                         ^
4 warnings generated.
python_bool_type.cpp:3790:26: warning: self-comparison always evaluates to true [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x == __pyx_v_x);
                         ^
python_bool_type.cpp:3816:26: warning: self-comparison always evaluates to false [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x != __pyx_v_x);
                         ^
python_bool_type.cpp:3962:26: warning: self-comparison always evaluates to true [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x == __pyx_v_x);
                         ^
python_bool_type.cpp:3988:26: warning: self-comparison always evaluates to false [-Wtautological-compare]
  __pyx_t_8 = (__pyx_v_x != __pyx_v_x);
                         ^
4 warnings generated.
tuple_unpack_string.c:870:13: warning: explicitly assigning a variable of type 'PyObject *' (aka 'struct _object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
1 warning generated.
tuple_unpack_string.cpp:870:13: warning: explicitly assigning a variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
  __pyx_t_6 = __pyx_t_6;
  ~~~~~~~~~ ^ ~~~~~~~~~
1 warning generated.
unused.c:599:18: warning: unused function '__pyx_f_6unused_c_unused_simple' [-Wunused-function]
static PyObject *__pyx_f_6unused_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                 ^
unused.c:644:18: warning: unused function '__pyx_f_6unused_c_unused_optional' [-Wunused-function]
static PyObject *__pyx_f_6unused_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_6unused_c_unused_optional ...
                 ^
2 warnings generated.
unused.cpp:599:18: warning: unused function '__pyx_f_6unused_c_unused_simple' [-Wunused-function]
static PyObject *__pyx_f_6unused_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                 ^
unused.cpp:644:18: warning: unused function '__pyx_f_6unused_c_unused_optional' [-Wunused-function]
static PyObject *__pyx_f_6unused_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_6unused_c_unused_optional ...
                 ^
2 warnings generated.
unused_args.c:624:18: warning: unused function '__pyx_f_11unused_args_c_unused_simple' [-Wunused-function]
static PyObject *__pyx_f_11unused_args_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                 ^
unused_args.c:669:18: warning: unused function '__pyx_f_11unused_args_c_unused_optional' [-Wunused-function]
static PyObject *__pyx_f_11unused_args_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct ...
                 ^
2 warnings generated.
unused_args.cpp:624:18: warning: unused function '__pyx_f_11unused_args_c_unused_simple' [-Wunused-function]
static PyObject *__pyx_f_11unused_args_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                 ^
unused_args.cpp:669:18: warning: unused function '__pyx_f_11unused_args_c_unused_optional' [-Wunused-function]
static PyObject *__pyx_f_11unused_args_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct ...
                 ^
2 warnings generated.
Exception ZeroDivisionError: 'integer division or modulo by zero' in  ignored
Exception ZeroDivisionError: 'integer division or modulo by zero' in  ignored
Exception ZeroDivisionError: 'integer division or modulo by zero' in  ignored
Exception ZeroDivisionError: 'integer division or modulo by zero' in  ignored
======================================================================
ERROR: <__main__._FakeClass object at 0x10b513050>
compiling (c) and running numpy_parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 754, in run_forked_test
    run_func(partial_result)
  File "runtests.py", line 731, in run_test
    tests = doctest.DocTestSuite(module_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2369, in DocTestSuite
    module = _normalize_module(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 203, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
ImportError: No module named numpy_parallel

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c) and running numpy_parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 711, in run
    self.run_tests(result)
  File "runtests.py", line 727, in run_tests
    self.run_doctests(self.module, result)
  File "runtests.py", line 733, in run_doctests
    run_forked_test(result, run_test, self.shortDescription(), self.fork)
  File "runtests.py", line 792, in run_forked_test
    (module_name, result_code))
Exception: Tests in module 'numpy_parallel' exited with status 1

======================================================================
ERROR: <__main__._FakeClass object at 0x109d57150>
compiling (cpp) and running numpy_parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 754, in run_forked_test
    run_func(partial_result)
  File "runtests.py", line 731, in run_test
    tests = doctest.DocTestSuite(module_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2369, in DocTestSuite
    module = _normalize_module(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 203, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
ImportError: No module named numpy_parallel

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (cpp) and running numpy_parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 711, in run
    self.run_tests(result)
  File "runtests.py", line 727, in run_tests
    self.run_doctests(self.module, result)
  File "runtests.py", line 733, in run_doctests
    run_forked_test(result, run_test, self.shortDescription(), self.fork)
  File "runtests.py", line 792, in run_forked_test
    (module_name, result_code))
Exception: Tests in module 'numpy_parallel' exited with status 1

======================================================================
ERROR: <__main__._FakeClass object at 0x10a642550>
compiling (c) and running parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 754, in run_forked_test
    run_func(partial_result)
  File "runtests.py", line 731, in run_test
    tests = doctest.DocTestSuite(module_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2369, in DocTestSuite
    module = _normalize_module(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 203, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
ImportError: No module named parallel

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c) and running parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 711, in run
    self.run_tests(result)
  File "runtests.py", line 727, in run_tests
    self.run_doctests(self.module, result)
  File "runtests.py", line 733, in run_doctests
    run_forked_test(result, run_test, self.shortDescription(), self.fork)
  File "runtests.py", line 792, in run_forked_test
    (module_name, result_code))
Exception: Tests in module 'parallel' exited with status 1

======================================================================
ERROR: <__main__._FakeClass object at 0x10a0209d0>
compiling (cpp) and running parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 754, in run_forked_test
    run_func(partial_result)
  File "runtests.py", line 731, in run_test
    tests = doctest.DocTestSuite(module_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2369, in DocTestSuite
    module = _normalize_module(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 203, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
ImportError: No module named parallel

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (cpp) and running parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 711, in run
    self.run_tests(result)
  File "runtests.py", line 727, in run_tests
    self.run_doctests(self.module, result)
  File "runtests.py", line 733, in run_doctests
    run_forked_test(result, run_test, self.shortDescription(), self.fork)
  File "runtests.py", line 792, in run_forked_test
    (module_name, result_code))
Exception: Tests in module 'parallel' exited with status 1

----------------------------------------------------------------------
Ran 6614 tests in 1905.331s

FAILED (errors=8)
ALL DONE